import React from "react";
import Head from "next/head";
import Banner from "@/components/common/Banner";
import Cartindex from "@/components/cart/Cart";
export default function takeout() {
  return (
    <div>
      <Head>
        <title>Cart - Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner type={"type"} text={'Cart'}/>
      <Cartindex/>
    </div>
  );
}
