import React from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import Banner from "@/components/common/Banner";
import Details from "@/components/details/Details";
export default function takeout() {
  const router = useRouter();
  console.log(router.query.productid);
  return (
    <div>
      <Head>
        <title>California Wraps | Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner type={"type"} />
      <Details/>
    </div>
  );
}
