import Head from "next/head";
import { Inter } from "next/font/google";
import Homeindex from "@/components/home/Home";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Root() {
  return (
    <>
      <Head>
        <title>Palkeeper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Homeindex />
      
    </>
  );
}